name: quran_mobile
description: Quran mobile Flutter app
publish_to: none
version: 1.0.6+7
environment:
  sdk: ">=3.11.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  flutter_riverpod: ^2.6.1
  flutter_animate: ^4.5.2
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.3.2
  adhan: ^2.0.0+1
  dio: ^5.7.0
  home_widget: ^0.7.0
  audioplayers: ^6.1.1
  flutter_local_notifications: 18.0.1
  timezone: 0.9.4
  share_plus: ^10.1.3
  path_provider: ^2.1.3
  confetti: ^0.8.0
  encrypt: ^5.0.3
  file_picker: ^11.0.2
  crypto: ^3.0.3
  fl_chart: ^0.70.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  archive: ^3.6.1
  audio_service: ^0.18.15
  audio_session: ^0.1.21
  flutter_markdown: ^0.7.3
  flutter_svg: ^2.3.0
  package_info_plus: ^9.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.14.1
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/themes/kaaba/
    - assets/themes/madinah/
    - assets/data/
    - assets/data/quran/
    - assets/reciters/
    - assets/companions/
    - assets/quran/svg/
    - assets/quran/json/
    - assets/data/packages/adhkar/
    - assets/data/packages/allah_names/
    - assets/data/packages/audio_metadata/
    - assets/data/packages/hadith/
    - assets/data/packages/quran/
    - assets/data/packages/sahaba/
    - assets/data/packages/seerah/
    - assets/data/packages/tajweed/
    - assets/data/packages/tajweed/001/
    - assets/data/packages/tajweed/002/
    - assets/data/packages/tajweed/003/
    - assets/data/packages/tajweed/004/
    - assets/data/packages/tajweed/005/
    - assets/data/packages/tajweed/006/
    - assets/data/packages/tajweed/007/
    - assets/data/packages/tajweed/008/
    - assets/data/packages/tajweed/009/
    - assets/data/packages/tajweed/010/
    - assets/data/packages/tajweed/011/
    - assets/data/packages/tajweed/012/
    - assets/data/packages/tajweed/013/
    - assets/data/packages/tajweed/014/
    - assets/data/packages/tajweed/015/
    - assets/data/packages/tajweed/016/
    - assets/data/packages/tajweed/017/
    - assets/data/packages/tajweed/018/
    - assets/data/packages/tajweed/019/
    - assets/data/packages/tajweed/020/
    - assets/data/packages/tajweed/021/
    - assets/data/packages/tajweed/022/
    - assets/data/packages/tajweed/023/
    - assets/data/packages/tajweed/024/
    - assets/data/packages/tajweed/025/
    - assets/data/packages/tajweed/026/
    - assets/data/packages/tajweed/027/
    - assets/data/packages/tajweed/028/
    - assets/data/packages/tajweed/029/
    - assets/data/packages/tajweed/030/
    - assets/data/packages/tajweed/031/
    - assets/data/packages/tajweed/032/
    - assets/data/packages/tajweed/033/
    - assets/data/packages/tajweed/034/
    - assets/data/packages/tajweed/035/
    - assets/data/packages/tajweed/036/
    - assets/data/packages/tajweed/037/
    - assets/data/packages/tajweed/038/
    - assets/data/packages/tajweed/039/
    - assets/data/packages/tajweed/040/
    - assets/data/packages/tajweed/041/
    - assets/data/packages/tajweed/042/
    - assets/data/packages/tajweed/043/
    - assets/data/packages/tajweed/044/
    - assets/data/packages/tajweed/045/
    - assets/data/packages/tajweed/046/
    - assets/data/packages/tajweed/047/
    - assets/data/packages/tajweed/048/
    - assets/data/packages/tajweed/049/
    - assets/data/packages/tajweed/050/
    - assets/data/packages/tajweed/051/
    - assets/data/packages/tajweed/052/
    - assets/data/packages/tajweed/053/
    - assets/data/packages/tajweed/054/
    - assets/data/packages/tajweed/055/
    - assets/data/packages/tajweed/056/
    - assets/data/packages/tajweed/057/
    - assets/data/packages/tajweed/058/
    - assets/data/packages/tajweed/059/
    - assets/data/packages/tajweed/060/
    - assets/data/packages/tajweed/061/
    - assets/data/packages/tajweed/062/
    - assets/data/packages/tajweed/063/
    - assets/data/packages/tajweed/064/
    - assets/data/packages/tajweed/065/
    - assets/data/packages/tajweed/066/
    - assets/data/packages/tajweed/067/
    - assets/data/packages/tajweed/068/
    - assets/data/packages/tajweed/069/
    - assets/data/packages/tajweed/070/
    - assets/data/packages/tajweed/071/
    - assets/data/packages/tajweed/072/
    - assets/data/packages/tajweed/073/
    - assets/data/packages/tajweed/074/
    - assets/data/packages/tajweed/075/
    - assets/data/packages/tajweed/076/
    - assets/data/packages/tajweed/077/
    - assets/data/packages/tajweed/078/
    - assets/data/packages/tajweed/079/
    - assets/data/packages/tajweed/080/
    - assets/data/packages/tajweed/081/
    - assets/data/packages/tajweed/082/
    - assets/data/packages/tajweed/083/
    - assets/data/packages/tajweed/084/
    - assets/data/packages/tajweed/085/
    - assets/data/packages/tajweed/086/
    - assets/data/packages/tajweed/087/
    - assets/data/packages/tajweed/088/
    - assets/data/packages/tajweed/089/
    - assets/data/packages/tajweed/090/
    - assets/data/packages/tajweed/091/
    - assets/data/packages/tajweed/092/
    - assets/data/packages/tajweed/093/
    - assets/data/packages/tajweed/094/
    - assets/data/packages/tajweed/095/
    - assets/data/packages/tajweed/096/
    - assets/data/packages/tajweed/097/
    - assets/data/packages/tajweed/098/
    - assets/data/packages/tajweed/099/
    - assets/data/packages/tajweed/100/
    - assets/data/packages/tajweed/101/
    - assets/data/packages/tajweed/102/
    - assets/data/packages/tajweed/103/
    - assets/data/packages/tajweed/104/
    - assets/data/packages/tajweed/105/
    - assets/data/packages/tajweed/106/
    - assets/data/packages/tajweed/107/
    - assets/data/packages/tajweed/108/
    - assets/data/packages/tajweed/109/
    - assets/data/packages/tajweed/110/
    - assets/data/packages/tajweed/111/
    - assets/data/packages/tajweed/112/
    - assets/data/packages/tajweed/113/
    - assets/data/packages/tajweed/114/
    - assets/data/packages/translations/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
    - family: AmiriQuran
      fonts:
        - asset: assets/fonts/tajweed_segment/AmiriQuran-Regular.ttf
    - family: ScheherazadeNew
      fonts:
        - asset: assets/fonts/tajweed_segment/ScheherazadeNew-Regular.ttf
    - family: Lateef
      fonts:
        - asset: assets/fonts/tajweed_segment/Lateef-Regular.ttf
    - family: NotoNaskhArabic
      fonts:
        - asset: assets/fonts/tajweed_segment/NotoNaskhArabic-VariableFont_wght.ttf
    - family: IBMPlexSansArabic
      fonts:
        - asset: assets/fonts/ar/UI/UX_IBMPlexSansArabic-Medium.ttf
          weight: 500
    - family: NizarNastaliq
      fonts:
        - asset: assets/fonts/ku/1_NizarNastaliqKurdish.ttf
