class RubElHizbData {
  static const List<Map<String, int>> list = [
    {
      'rub_number': 1,
      'start_surah': 1,
      'start_ayah': 1,
      'start_page': 1,
    },
    {
      'rub_number': 2,
      'start_surah': 2,
      'start_ayah': 26,
      'start_page': 5,
    },
    {
      'rub_number': 3,
      'start_surah': 2,
      'start_ayah': 44,
      'start_page': 7,
    },
    {
      'rub_number': 4,
      'start_surah': 2,
      'start_ayah': 60,
      'start_page': 9,
    },
    {
      'rub_number': 5,
      'start_surah': 2,
      'start_ayah': 75,
      'start_page': 11,
    },
    {
      'rub_number': 6,
      'start_surah': 2,
      'start_ayah': 92,
      'start_page': 14,
    },
    {
      'rub_number': 7,
      'start_surah': 2,
      'start_ayah': 106,
      'start_page': 17,
    },
    {
      'rub_number': 8,
      'start_surah': 2,
      'start_ayah': 124,
      'start_page': 19,
    },
    {
      'rub_number': 9,
      'start_surah': 2,
      'start_ayah': 142,
      'start_page': 22,
    },
    {
      'rub_number': 10,
      'start_surah': 2,
      'start_ayah': 158,
      'start_page': 24,
    },
    {
      'rub_number': 11,
      'start_surah': 2,
      'start_ayah': 177,
      'start_page': 27,
    },
    {
      'rub_number': 12,
      'start_surah': 2,
      'start_ayah': 189,
      'start_page': 29,
    },
    {
      'rub_number': 13,
      'start_surah': 2,
      'start_ayah': 203,
      'start_page': 32,
    },
    {
      'rub_number': 14,
      'start_surah': 2,
      'start_ayah': 219,
      'start_page': 34,
    },
    {
      'rub_number': 15,
      'start_surah': 2,
      'start_ayah': 233,
      'start_page': 37,
    },
    {
      'rub_number': 16,
      'start_surah': 2,
      'start_ayah': 243,
      'start_page': 39,
    },
    {
      'rub_number': 17,
      'start_surah': 2,
      'start_ayah': 253,
      'start_page': 42,
    },
    {
      'rub_number': 18,
      'start_surah': 2,
      'start_ayah': 263,
      'start_page': 44,
    },
    {
      'rub_number': 19,
      'start_surah': 2,
      'start_ayah': 272,
      'start_page': 46,
    },
    {
      'rub_number': 20,
      'start_surah': 2,
      'start_ayah': 283,
      'start_page': 49,
    },
    {
      'rub_number': 21,
      'start_surah': 3,
      'start_ayah': 15,
      'start_page': 51,
    },
    {
      'rub_number': 22,
      'start_surah': 3,
      'start_ayah': 33,
      'start_page': 54,
    },
    {
      'rub_number': 23,
      'start_surah': 3,
      'start_ayah': 52,
      'start_page': 56,
    },
    {
      'rub_number': 24,
      'start_surah': 3,
      'start_ayah': 75,
      'start_page': 59,
    },
    {
      'rub_number': 25,
      'start_surah': 3,
      'start_ayah': 93,
      'start_page': 62,
    },
    {
      'rub_number': 26,
      'start_surah': 3,
      'start_ayah': 113,
      'start_page': 64,
    },
    {
      'rub_number': 27,
      'start_surah': 3,
      'start_ayah': 133,
      'start_page': 67,
    },
    {
      'rub_number': 28,
      'start_surah': 3,
      'start_ayah': 153,
      'start_page': 69,
    },
    {
      'rub_number': 29,
      'start_surah': 3,
      'start_ayah': 171,
      'start_page': 72,
    },
    {
      'rub_number': 30,
      'start_surah': 3,
      'start_ayah': 186,
      'start_page': 74,
    },
    {
      'rub_number': 31,
      'start_surah': 4,
      'start_ayah': 1,
      'start_page': 77,
    },
    {
      'rub_number': 32,
      'start_surah': 4,
      'start_ayah': 12,
      'start_page': 79,
    },
    {
      'rub_number': 33,
      'start_surah': 4,
      'start_ayah': 24,
      'start_page': 82,
    },
    {
      'rub_number': 34,
      'start_surah': 4,
      'start_ayah': 36,
      'start_page': 84,
    },
    {
      'rub_number': 35,
      'start_surah': 4,
      'start_ayah': 58,
      'start_page': 87,
    },
    {
      'rub_number': 36,
      'start_surah': 4,
      'start_ayah': 74,
      'start_page': 89,
    },
    {
      'rub_number': 37,
      'start_surah': 4,
      'start_ayah': 88,
      'start_page': 92,
    },
    {
      'rub_number': 38,
      'start_surah': 4,
      'start_ayah': 100,
      'start_page': 94,
    },
    {
      'rub_number': 39,
      'start_surah': 4,
      'start_ayah': 114,
      'start_page': 97,
    },
    {
      'rub_number': 40,
      'start_surah': 4,
      'start_ayah': 135,
      'start_page': 100,
    },
    {
      'rub_number': 41,
      'start_surah': 4,
      'start_ayah': 148,
      'start_page': 102,
    },
    {
      'rub_number': 42,
      'start_surah': 4,
      'start_ayah': 163,
      'start_page': 104,
    },
    {
      'rub_number': 43,
      'start_surah': 5,
      'start_ayah': 1,
      'start_page': 106,
    },
    {
      'rub_number': 44,
      'start_surah': 5,
      'start_ayah': 12,
      'start_page': 109,
    },
    {
      'rub_number': 45,
      'start_surah': 5,
      'start_ayah': 27,
      'start_page': 112,
    },
    {
      'rub_number': 46,
      'start_surah': 5,
      'start_ayah': 41,
      'start_page': 114,
    },
    {
      'rub_number': 47,
      'start_surah': 5,
      'start_ayah': 51,
      'start_page': 117,
    },
    {
      'rub_number': 48,
      'start_surah': 5,
      'start_ayah': 67,
      'start_page': 119,
    },
    {
      'rub_number': 49,
      'start_surah': 5,
      'start_ayah': 82,
      'start_page': 121,
    },
    {
      'rub_number': 50,
      'start_surah': 5,
      'start_ayah': 97,
      'start_page': 124,
    },
    {
      'rub_number': 51,
      'start_surah': 5,
      'start_ayah': 109,
      'start_page': 126,
    },
    {
      'rub_number': 52,
      'start_surah': 6,
      'start_ayah': 13,
      'start_page': 129,
    },
    {
      'rub_number': 53,
      'start_surah': 6,
      'start_ayah': 36,
      'start_page': 132,
    },
    {
      'rub_number': 54,
      'start_surah': 6,
      'start_ayah': 59,
      'start_page': 134,
    },
    {
      'rub_number': 55,
      'start_surah': 6,
      'start_ayah': 74,
      'start_page': 137,
    },
    {
      'rub_number': 56,
      'start_surah': 6,
      'start_ayah': 95,
      'start_page': 140,
    },
    {
      'rub_number': 57,
      'start_surah': 6,
      'start_ayah': 111,
      'start_page': 142,
    },
    {
      'rub_number': 58,
      'start_surah': 6,
      'start_ayah': 127,
      'start_page': 144,
    },
    {
      'rub_number': 59,
      'start_surah': 6,
      'start_ayah': 141,
      'start_page': 146,
    },
    {
      'rub_number': 60,
      'start_surah': 6,
      'start_ayah': 151,
      'start_page': 148,
    },
    {
      'rub_number': 61,
      'start_surah': 7,
      'start_ayah': 1,
      'start_page': 151,
    },
    {
      'rub_number': 62,
      'start_surah': 7,
      'start_ayah': 31,
      'start_page': 154,
    },
    {
      'rub_number': 63,
      'start_surah': 7,
      'start_ayah': 47,
      'start_page': 156,
    },
    {
      'rub_number': 64,
      'start_surah': 7,
      'start_ayah': 65,
      'start_page': 158,
    },
    {
      'rub_number': 65,
      'start_surah': 7,
      'start_ayah': 88,
      'start_page': 162,
    },
    {
      'rub_number': 66,
      'start_surah': 7,
      'start_ayah': 117,
      'start_page': 164,
    },
    {
      'rub_number': 67,
      'start_surah': 7,
      'start_ayah': 142,
      'start_page': 167,
    },
    {
      'rub_number': 68,
      'start_surah': 7,
      'start_ayah': 156,
      'start_page': 170,
    },
    {
      'rub_number': 69,
      'start_surah': 7,
      'start_ayah': 171,
      'start_page': 173,
    },
    {
      'rub_number': 70,
      'start_surah': 7,
      'start_ayah': 189,
      'start_page': 175,
    },
    {
      'rub_number': 71,
      'start_surah': 8,
      'start_ayah': 1,
      'start_page': 177,
    },
    {
      'rub_number': 72,
      'start_surah': 8,
      'start_ayah': 22,
      'start_page': 179,
    },
    {
      'rub_number': 73,
      'start_surah': 8,
      'start_ayah': 41,
      'start_page': 182,
    },
    {
      'rub_number': 74,
      'start_surah': 8,
      'start_ayah': 61,
      'start_page': 184,
    },
    {
      'rub_number': 75,
      'start_surah': 9,
      'start_ayah': 1,
      'start_page': 187,
    },
    {
      'rub_number': 76,
      'start_surah': 9,
      'start_ayah': 19,
      'start_page': 189,
    },
    {
      'rub_number': 77,
      'start_surah': 9,
      'start_ayah': 34,
      'start_page': 192,
    },
    {
      'rub_number': 78,
      'start_surah': 9,
      'start_ayah': 46,
      'start_page': 194,
    },
    {
      'rub_number': 79,
      'start_surah': 9,
      'start_ayah': 60,
      'start_page': 196,
    },
    {
      'rub_number': 80,
      'start_surah': 9,
      'start_ayah': 75,
      'start_page': 199,
    },
    {
      'rub_number': 81,
      'start_surah': 9,
      'start_ayah': 93,
      'start_page': 201,
    },
    {
      'rub_number': 82,
      'start_surah': 9,
      'start_ayah': 111,
      'start_page': 204,
    },
    {
      'rub_number': 83,
      'start_surah': 9,
      'start_ayah': 122,
      'start_page': 206,
    },
    {
      'rub_number': 84,
      'start_surah': 10,
      'start_ayah': 11,
      'start_page': 209,
    },
    {
      'rub_number': 85,
      'start_surah': 10,
      'start_ayah': 26,
      'start_page': 212,
    },
    {
      'rub_number': 86,
      'start_surah': 10,
      'start_ayah': 53,
      'start_page': 214,
    },
    {
      'rub_number': 87,
      'start_surah': 10,
      'start_ayah': 71,
      'start_page': 217,
    },
    {
      'rub_number': 88,
      'start_surah': 10,
      'start_ayah': 90,
      'start_page': 219,
    },
    {
      'rub_number': 89,
      'start_surah': 11,
      'start_ayah': 6,
      'start_page': 222,
    },
    {
      'rub_number': 90,
      'start_surah': 11,
      'start_ayah': 24,
      'start_page': 224,
    },
    {
      'rub_number': 91,
      'start_surah': 11,
      'start_ayah': 41,
      'start_page': 226,
    },
    {
      'rub_number': 92,
      'start_surah': 11,
      'start_ayah': 61,
      'start_page': 228,
    },
    {
      'rub_number': 93,
      'start_surah': 11,
      'start_ayah': 84,
      'start_page': 231,
    },
    {
      'rub_number': 94,
      'start_surah': 11,
      'start_ayah': 108,
      'start_page': 233,
    },
    {
      'rub_number': 95,
      'start_surah': 12,
      'start_ayah': 7,
      'start_page': 236,
    },
    {
      'rub_number': 96,
      'start_surah': 12,
      'start_ayah': 30,
      'start_page': 238,
    },
    {
      'rub_number': 97,
      'start_surah': 12,
      'start_ayah': 53,
      'start_page': 242,
    },
    {
      'rub_number': 98,
      'start_surah': 12,
      'start_ayah': 77,
      'start_page': 244,
    },
    {
      'rub_number': 99,
      'start_surah': 12,
      'start_ayah': 101,
      'start_page': 247,
    },
    {
      'rub_number': 100,
      'start_surah': 13,
      'start_ayah': 5,
      'start_page': 249,
    },
    {
      'rub_number': 101,
      'start_surah': 13,
      'start_ayah': 19,
      'start_page': 252,
    },
    {
      'rub_number': 102,
      'start_surah': 13,
      'start_ayah': 35,
      'start_page': 254,
    },
    {
      'rub_number': 103,
      'start_surah': 14,
      'start_ayah': 10,
      'start_page': 256,
    },
    {
      'rub_number': 104,
      'start_surah': 14,
      'start_ayah': 28,
      'start_page': 259,
    },
    {
      'rub_number': 105,
      'start_surah': 15,
      'start_ayah': 1,
      'start_page': 262,
    },
    {
      'rub_number': 106,
      'start_surah': 15,
      'start_ayah': 50,
      'start_page': 264,
    },
    {
      'rub_number': 107,
      'start_surah': 16,
      'start_ayah': 1,
      'start_page': 267,
    },
    {
      'rub_number': 108,
      'start_surah': 16,
      'start_ayah': 30,
      'start_page': 270,
    },
    {
      'rub_number': 109,
      'start_surah': 16,
      'start_ayah': 51,
      'start_page': 272,
    },
    {
      'rub_number': 110,
      'start_surah': 16,
      'start_ayah': 75,
      'start_page': 275,
    },
    {
      'rub_number': 111,
      'start_surah': 16,
      'start_ayah': 90,
      'start_page': 277,
    },
    {
      'rub_number': 112,
      'start_surah': 16,
      'start_ayah': 111,
      'start_page': 280,
    },
    {
      'rub_number': 113,
      'start_surah': 17,
      'start_ayah': 1,
      'start_page': 282,
    },
    {
      'rub_number': 114,
      'start_surah': 17,
      'start_ayah': 23,
      'start_page': 284,
    },
    {
      'rub_number': 115,
      'start_surah': 17,
      'start_ayah': 50,
      'start_page': 287,
    },
    {
      'rub_number': 116,
      'start_surah': 17,
      'start_ayah': 70,
      'start_page': 289,
    },
    {
      'rub_number': 117,
      'start_surah': 17,
      'start_ayah': 99,
      'start_page': 292,
    },
    {
      'rub_number': 118,
      'start_surah': 18,
      'start_ayah': 17,
      'start_page': 295,
    },
    {
      'rub_number': 119,
      'start_surah': 18,
      'start_ayah': 32,
      'start_page': 297,
    },
    {
      'rub_number': 120,
      'start_surah': 18,
      'start_ayah': 51,
      'start_page': 299,
    },
    {
      'rub_number': 121,
      'start_surah': 18,
      'start_ayah': 75,
      'start_page': 302,
    },
    {
      'rub_number': 122,
      'start_surah': 18,
      'start_ayah': 99,
      'start_page': 304,
    },
    {
      'rub_number': 123,
      'start_surah': 19,
      'start_ayah': 22,
      'start_page': 306,
    },
    {
      'rub_number': 124,
      'start_surah': 19,
      'start_ayah': 59,
      'start_page': 309,
    },
    {
      'rub_number': 125,
      'start_surah': 20,
      'start_ayah': 1,
      'start_page': 312,
    },
    {
      'rub_number': 126,
      'start_surah': 20,
      'start_ayah': 55,
      'start_page': 315,
    },
    {
      'rub_number': 127,
      'start_surah': 20,
      'start_ayah': 83,
      'start_page': 317,
    },
    {
      'rub_number': 128,
      'start_surah': 20,
      'start_ayah': 111,
      'start_page': 319,
    },
    {
      'rub_number': 129,
      'start_surah': 21,
      'start_ayah': 1,
      'start_page': 322,
    },
    {
      'rub_number': 130,
      'start_surah': 21,
      'start_ayah': 29,
      'start_page': 324,
    },
    {
      'rub_number': 131,
      'start_surah': 21,
      'start_ayah': 51,
      'start_page': 326,
    },
    {
      'rub_number': 132,
      'start_surah': 21,
      'start_ayah': 83,
      'start_page': 329,
    },
    {
      'rub_number': 133,
      'start_surah': 22,
      'start_ayah': 1,
      'start_page': 332,
    },
    {
      'rub_number': 134,
      'start_surah': 22,
      'start_ayah': 19,
      'start_page': 334,
    },
    {
      'rub_number': 135,
      'start_surah': 22,
      'start_ayah': 38,
      'start_page': 336,
    },
    {
      'rub_number': 136,
      'start_surah': 22,
      'start_ayah': 60,
      'start_page': 339,
    },
    {
      'rub_number': 137,
      'start_surah': 23,
      'start_ayah': 1,
      'start_page': 342,
    },
    {
      'rub_number': 138,
      'start_surah': 23,
      'start_ayah': 36,
      'start_page': 344,
    },
    {
      'rub_number': 139,
      'start_surah': 23,
      'start_ayah': 75,
      'start_page': 347,
    },
    {
      'rub_number': 140,
      'start_surah': 24,
      'start_ayah': 1,
      'start_page': 350,
    },
    {
      'rub_number': 141,
      'start_surah': 24,
      'start_ayah': 21,
      'start_page': 352,
    },
    {
      'rub_number': 142,
      'start_surah': 24,
      'start_ayah': 35,
      'start_page': 354,
    },
    {
      'rub_number': 143,
      'start_surah': 24,
      'start_ayah': 53,
      'start_page': 356,
    },
    {
      'rub_number': 144,
      'start_surah': 25,
      'start_ayah': 1,
      'start_page': 359,
    },
    {
      'rub_number': 145,
      'start_surah': 25,
      'start_ayah': 21,
      'start_page': 362,
    },
    {
      'rub_number': 146,
      'start_surah': 25,
      'start_ayah': 53,
      'start_page': 364,
    },
    {
      'rub_number': 147,
      'start_surah': 26,
      'start_ayah': 1,
      'start_page': 367,
    },
    {
      'rub_number': 148,
      'start_surah': 26,
      'start_ayah': 52,
      'start_page': 369,
    },
    {
      'rub_number': 149,
      'start_surah': 26,
      'start_ayah': 111,
      'start_page': 371,
    },
    {
      'rub_number': 150,
      'start_surah': 26,
      'start_ayah': 181,
      'start_page': 374,
    },
    {
      'rub_number': 151,
      'start_surah': 27,
      'start_ayah': 1,
      'start_page': 377,
    },
    {
      'rub_number': 152,
      'start_surah': 27,
      'start_ayah': 27,
      'start_page': 379,
    },
    {
      'rub_number': 153,
      'start_surah': 27,
      'start_ayah': 56,
      'start_page': 382,
    },
    {
      'rub_number': 154,
      'start_surah': 27,
      'start_ayah': 82,
      'start_page': 384,
    },
    {
      'rub_number': 155,
      'start_surah': 28,
      'start_ayah': 12,
      'start_page': 386,
    },
    {
      'rub_number': 156,
      'start_surah': 28,
      'start_ayah': 29,
      'start_page': 389,
    },
    {
      'rub_number': 157,
      'start_surah': 28,
      'start_ayah': 51,
      'start_page': 392,
    },
    {
      'rub_number': 158,
      'start_surah': 28,
      'start_ayah': 76,
      'start_page': 394,
    },
    {
      'rub_number': 159,
      'start_surah': 29,
      'start_ayah': 1,
      'start_page': 396,
    },
    {
      'rub_number': 160,
      'start_surah': 29,
      'start_ayah': 26,
      'start_page': 399,
    },
    {
      'rub_number': 161,
      'start_surah': 29,
      'start_ayah': 46,
      'start_page': 402,
    },
    {
      'rub_number': 162,
      'start_surah': 30,
      'start_ayah': 1,
      'start_page': 404,
    },
    {
      'rub_number': 163,
      'start_surah': 30,
      'start_ayah': 31,
      'start_page': 407,
    },
    {
      'rub_number': 164,
      'start_surah': 30,
      'start_ayah': 54,
      'start_page': 410,
    },
    {
      'rub_number': 165,
      'start_surah': 31,
      'start_ayah': 22,
      'start_page': 413,
    },
    {
      'rub_number': 166,
      'start_surah': 32,
      'start_ayah': 11,
      'start_page': 415,
    },
    {
      'rub_number': 167,
      'start_surah': 33,
      'start_ayah': 1,
      'start_page': 418,
    },
    {
      'rub_number': 168,
      'start_surah': 33,
      'start_ayah': 18,
      'start_page': 420,
    },
    {
      'rub_number': 169,
      'start_surah': 33,
      'start_ayah': 31,
      'start_page': 422,
    },
    {
      'rub_number': 170,
      'start_surah': 33,
      'start_ayah': 51,
      'start_page': 425,
    },
    {
      'rub_number': 171,
      'start_surah': 33,
      'start_ayah': 60,
      'start_page': 426,
    },
    {
      'rub_number': 172,
      'start_surah': 34,
      'start_ayah': 10,
      'start_page': 429,
    },
    {
      'rub_number': 173,
      'start_surah': 34,
      'start_ayah': 24,
      'start_page': 431,
    },
    {
      'rub_number': 174,
      'start_surah': 34,
      'start_ayah': 46,
      'start_page': 433,
    },
    {
      'rub_number': 175,
      'start_surah': 35,
      'start_ayah': 15,
      'start_page': 436,
    },
    {
      'rub_number': 176,
      'start_surah': 35,
      'start_ayah': 41,
      'start_page': 439,
    },
    {
      'rub_number': 177,
      'start_surah': 36,
      'start_ayah': 28,
      'start_page': 442,
    },
    {
      'rub_number': 178,
      'start_surah': 36,
      'start_ayah': 60,
      'start_page': 444,
    },
    {
      'rub_number': 179,
      'start_surah': 37,
      'start_ayah': 22,
      'start_page': 446,
    },
    {
      'rub_number': 180,
      'start_surah': 37,
      'start_ayah': 83,
      'start_page': 449,
    },
    {
      'rub_number': 181,
      'start_surah': 37,
      'start_ayah': 145,
      'start_page': 451,
    },
    {
      'rub_number': 182,
      'start_surah': 38,
      'start_ayah': 21,
      'start_page': 454,
    },
    {
      'rub_number': 183,
      'start_surah': 38,
      'start_ayah': 52,
      'start_page': 456,
    },
    {
      'rub_number': 184,
      'start_surah': 39,
      'start_ayah': 8,
      'start_page': 459,
    },
    {
      'rub_number': 185,
      'start_surah': 39,
      'start_ayah': 32,
      'start_page': 462,
    },
    {
      'rub_number': 186,
      'start_surah': 39,
      'start_ayah': 53,
      'start_page': 464,
    },
    {
      'rub_number': 187,
      'start_surah': 40,
      'start_ayah': 1,
      'start_page': 467,
    },
    {
      'rub_number': 188,
      'start_surah': 40,
      'start_ayah': 21,
      'start_page': 469,
    },
    {
      'rub_number': 189,
      'start_surah': 40,
      'start_ayah': 41,
      'start_page': 472,
    },
    {
      'rub_number': 190,
      'start_surah': 40,
      'start_ayah': 66,
      'start_page': 474,
    },
    {
      'rub_number': 191,
      'start_surah': 41,
      'start_ayah': 9,
      'start_page': 477,
    },
    {
      'rub_number': 192,
      'start_surah': 41,
      'start_ayah': 25,
      'start_page': 479,
    },
    {
      'rub_number': 193,
      'start_surah': 41,
      'start_ayah': 47,
      'start_page': 482,
    },
    {
      'rub_number': 194,
      'start_surah': 42,
      'start_ayah': 13,
      'start_page': 484,
    },
    {
      'rub_number': 195,
      'start_surah': 42,
      'start_ayah': 27,
      'start_page': 486,
    },
    {
      'rub_number': 196,
      'start_surah': 42,
      'start_ayah': 51,
      'start_page': 488,
    },
    {
      'rub_number': 197,
      'start_surah': 43,
      'start_ayah': 24,
      'start_page': 491,
    },
    {
      'rub_number': 198,
      'start_surah': 43,
      'start_ayah': 57,
      'start_page': 493,
    },
    {
      'rub_number': 199,
      'start_surah': 44,
      'start_ayah': 17,
      'start_page': 496,
    },
    {
      'rub_number': 200,
      'start_surah': 45,
      'start_ayah': 12,
      'start_page': 499,
    },
    {
      'rub_number': 201,
      'start_surah': 46,
      'start_ayah': 1,
      'start_page': 502,
    },
    {
      'rub_number': 202,
      'start_surah': 46,
      'start_ayah': 21,
      'start_page': 505,
    },
    {
      'rub_number': 203,
      'start_surah': 47,
      'start_ayah': 10,
      'start_page': 507,
    },
    {
      'rub_number': 204,
      'start_surah': 47,
      'start_ayah': 33,
      'start_page': 510,
    },
    {
      'rub_number': 205,
      'start_surah': 48,
      'start_ayah': 18,
      'start_page': 513,
    },
    {
      'rub_number': 206,
      'start_surah': 49,
      'start_ayah': 1,
      'start_page': 515,
    },
    {
      'rub_number': 207,
      'start_surah': 49,
      'start_ayah': 14,
      'start_page': 517,
    },
    {
      'rub_number': 208,
      'start_surah': 50,
      'start_ayah': 27,
      'start_page': 519,
    },
    {
      'rub_number': 209,
      'start_surah': 51,
      'start_ayah': 31,
      'start_page': 522,
    },
    {
      'rub_number': 210,
      'start_surah': 52,
      'start_ayah': 24,
      'start_page': 524,
    },
    {
      'rub_number': 211,
      'start_surah': 53,
      'start_ayah': 26,
      'start_page': 526,
    },
    {
      'rub_number': 212,
      'start_surah': 54,
      'start_ayah': 9,
      'start_page': 529,
    },
    {
      'rub_number': 213,
      'start_surah': 55,
      'start_ayah': 1,
      'start_page': 531,
    },
    {
      'rub_number': 214,
      'start_surah': 56,
      'start_ayah': 1,
      'start_page': 534,
    },
    {
      'rub_number': 215,
      'start_surah': 56,
      'start_ayah': 75,
      'start_page': 536,
    },
    {
      'rub_number': 216,
      'start_surah': 57,
      'start_ayah': 16,
      'start_page': 539,
    },
    {
      'rub_number': 217,
      'start_surah': 58,
      'start_ayah': 1,
      'start_page': 542,
    },
    {
      'rub_number': 218,
      'start_surah': 58,
      'start_ayah': 14,
      'start_page': 544,
    },
    {
      'rub_number': 219,
      'start_surah': 59,
      'start_ayah': 11,
      'start_page': 547,
    },
    {
      'rub_number': 220,
      'start_surah': 60,
      'start_ayah': 7,
      'start_page': 550,
    },
    {
      'rub_number': 221,
      'start_surah': 62,
      'start_ayah': 1,
      'start_page': 553,
    },
    {
      'rub_number': 222,
      'start_surah': 63,
      'start_ayah': 4,
      'start_page': 554,
    },
    {
      'rub_number': 223,
      'start_surah': 65,
      'start_ayah': 1,
      'start_page': 558,
    },
    {
      'rub_number': 224,
      'start_surah': 66,
      'start_ayah': 1,
      'start_page': 560,
    },
    {
      'rub_number': 225,
      'start_surah': 67,
      'start_ayah': 1,
      'start_page': 562,
    },
    {
      'rub_number': 226,
      'start_surah': 68,
      'start_ayah': 1,
      'start_page': 564,
    },
    {
      'rub_number': 227,
      'start_surah': 69,
      'start_ayah': 1,
      'start_page': 566,
    },
    {
      'rub_number': 228,
      'start_surah': 70,
      'start_ayah': 19,
      'start_page': 569,
    },
    {
      'rub_number': 229,
      'start_surah': 72,
      'start_ayah': 1,
      'start_page': 572,
    },
    {
      'rub_number': 230,
      'start_surah': 73,
      'start_ayah': 20,
      'start_page': 575,
    },
    {
      'rub_number': 231,
      'start_surah': 75,
      'start_ayah': 1,
      'start_page': 577,
    },
    {
      'rub_number': 232,
      'start_surah': 76,
      'start_ayah': 19,
      'start_page': 579,
    },
    {
      'rub_number': 233,
      'start_surah': 78,
      'start_ayah': 1,
      'start_page': 582,
    },
    {
      'rub_number': 234,
      'start_surah': 80,
      'start_ayah': 1,
      'start_page': 585,
    },
    {
      'rub_number': 235,
      'start_surah': 82,
      'start_ayah': 1,
      'start_page': 587,
    },
    {
      'rub_number': 236,
      'start_surah': 84,
      'start_ayah': 1,
      'start_page': 589,
    },
    {
      'rub_number': 237,
      'start_surah': 87,
      'start_ayah': 1,
      'start_page': 591,
    },
    {
      'rub_number': 238,
      'start_surah': 90,
      'start_ayah': 1,
      'start_page': 594,
    },
    {
      'rub_number': 239,
      'start_surah': 94,
      'start_ayah': 1,
      'start_page': 596,
    },
    {
      'rub_number': 240,
      'start_surah': 100,
      'start_ayah': 9,
      'start_page': 599,
    },
  ];
}
